language: node_js
node_js:
- '6'
script: npm test
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_d98a3227cf72_key -iv $encrypted_d98a3227cf72_iv
  -in keypair.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
